// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDircw8nUpqXb8xiMLr1QsDe_usdrMKjwo',
    appId: '1:741821520665:web:d51568df108d5197858388',
    messagingSenderId: '741821520665',
    projectId: 'dsi-heart',
    authDomain: 'dsi-heart.firebaseapp.com',
    storageBucket: 'dsi-heart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQvlxPBQ_7_XSxFeBQ__DRICTaGovc-rk',
    appId: '1:741821520665:android:2a986ecac4f79ed0858388',
    messagingSenderId: '741821520665',
    projectId: 'dsi-heart',
    storageBucket: 'dsi-heart.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDircw8nUpqXb8xiMLr1QsDe_usdrMKjwo',
    appId: '1:741821520665:web:d05e6ebf21ab2818858388',
    messagingSenderId: '741821520665',
    projectId: 'dsi-heart',
    authDomain: 'dsi-heart.firebaseapp.com',
    storageBucket: 'dsi-heart.appspot.com',
  );

}